package com.example.ui

object Loc {
    fun get(key: String, nativeLang: String): String {
        val lang = nativeLang.lowercase()
        return when {
            lang.contains("alem") || lang.contains("deutsch") || lang.contains("german") -> when (key) {
                "step" -> "Schritt"
                "of" -> "von"
                "next" -> "Weiter"
                "back" -> "Zurück"
                "finish" -> "Abschließen"
                "app_lang" -> "App-Sprache"
                "native_lang" -> "Muttersprache"
                "secondary_lang" -> "Zweitsprache (Optional)"
                "study_lang" -> "Lernsprache"
                "lang_config" -> "Sprachkonfiguration"
                "lang_subtitle" -> "Wählen Sie die Sprachen, die Sie verwenden und lernen möchten."
                "study_level" -> "Niveau der Lernsprache"
                "level_desc" -> "Wählen Sie Ihr aktuelles Niveau in %s. Dies hilft, die Schwierigkeit anzupassen."
                "choose_interests" -> "Wählen Sie Ihre Interessen"
                "interests_desc" -> "Wir empfehlen Texte basierend auf den ausgewählten Unterkategorien."
                "reading" -> "Lesen"
                "tests" -> "Tests"
                "vocabulary" -> "Vokabeln"
                "profile" -> "Profil"
                "publish" -> "Veröffentlichen"
                "my_vocab" -> "Mein Wortschatz"
                "vocab_desc" -> "Wörter und Ausdrücke, die Sie beim Lesen für das Offline-Studium gespeichert haben."
                "vocab_empty" -> "Leerer Wortschatz"
                "vocab_empty_desc" -> "Klicken Sie beim Lesen auf die orangefarbenen Wörter, um die Übersetzung zu sehen und sie hier hinzuzufügen!"
                "meaning" -> "Bedeutung"
                "example" -> "Praktisches Beispiel"
                "my_profile" -> "Mein Profil"
                "student_of" -> "Lernt %s"
                "level" -> "Niveau"
                "native_in" -> "Muttersprache: %s"
                "daily_goal" -> "TÄGLICHES ZIEL"
                "streak" -> "Streak"
                "days" -> "Tage"
                "publisher" -> "Herausgeber"
                "approved" -> "Zugelassen"
                "pending" -> "Ausstehend"
                "my_hobbies" -> "Meine Interessen & Hobbies"
                "reset_onboarding" -> "Onboarding zurücksetzen"
                "create_story" -> "Neue Geschichte erstellen"
                "publish_community" -> "Veröffentlichen Sie Texte für die Community in %s"
                "orig_title" -> "Originaltitel (%s)"
                "trans_title" -> "Übersetzter Titel (Deutsch)"
                "story_text" -> "Geschichtentext (%s)"
                "story_trans" -> "Übersetzung der Geschichte (Deutsch)"
                "diff_level" -> "Schwierigkeitsgrad auswählen"
                "category" -> "Kategorie"
                "cover_url" -> "Cover-Bild-URL (Optional)"
                "tags" -> "Tags (durch Komma getrennt)"
                "publish_btn" -> "Geschichte veröffentlichen"
                "fill_required" -> "Bitte füllen Sie alle Pflichtfelder aus!"
                "publish_success" -> "Geschichte erfolgreich veröffentlicht!"
                "publish_locked" -> "Veröffentlichung gesperrt"
                "publish_locked_desc" -> "Um neue Geschichten in %s zu veröffentlichen, müssen Sie die 20-Fragen-Leseprüfung mit 100%% bestehen."
                "take_test" -> "Leseprüfung machen"
                "dict_tap" -> "Tippen Sie auf ein hervorgehobenes Wort, um das Wörterbuch zu öffnen:"
                "prof_test" -> "Profizienztag in %s"
                "test_desc" -> "Erreichen Sie 100% (20/20), um die Veröffentlichung von Geschichten freizuschalten!"
                "question" -> "Frage"
                "corrects" -> "Richtige"
                "confirm" -> "Antwort bestätigen"
                "test_finished" -> "Test beendet!"
                "not_this_time" -> "Nicht dieses Mal!"
                "got_correct" -> "Sie haben %d von %d Fragen richtig beantwortet (%d%%)"
                "pub_unlocked" -> "VERÖFFENTLICHUNG FREIGESCHALTET!"
                "congrats_desc" -> "Unglaublich! Sie haben alle Fragen richtig beantwortet. Sie dürfen jetzt neue Geschichten auf der Plattform veröffentlichen!"
                "how_to_unlock" -> "Wie freischalten?"
                "unlock_desc" -> "Um die pädagogische Qualität zu sichern, können nur Benutzer mit 100% im Test Geschichten erstellen. Lernen Sie mehr und versuchen Sie es erneut!"
                "try_again" -> "Erneut versuchen"
                "original" -> "Original"
                "translation" -> "Übersetzung"
                "none" -> "Keine"
                else -> key
            }
            lang.contains("espan") || lang.contains("spanish") -> when (key) {
                "step" -> "Paso"
                "of" -> "de"
                "next" -> "Continuar"
                "back" -> "Volver"
                "finish" -> "Finalizar"
                "app_lang" -> "Idioma de la Aplicación"
                "native_lang" -> "Tu Idioma Nativo"
                "secondary_lang" -> "Idioma Secundario (Opcional)"
                "study_lang" -> "Idioma en Estudio"
                "lang_config" -> "Configuración de Idiomas"
                "lang_subtitle" -> "Elige los idiomas que usas y el que deseas estudiar."
                "study_level" -> "Nivel del Idioma en Estudio"
                "level_desc" -> "Selecciona tu nivel actual en %s. Esto ayudará a adaptar la dificultad."
                "choose_interests" -> "Elige tus Intereses"
                "interests_desc" -> "Recomendamos textos basados en las subcategorías seleccionadas."
                "reading" -> "Lectura"
                "tests" -> "Pruebas"
                "vocabulary" -> "Vocabulario"
                "profile" -> "Perfil"
                "publish" -> "Publicar"
                "my_vocab" -> "Mi Vocabulario"
                "vocab_desc" -> "Palabras y expresiones que guardaste durante las lecturas para estudiar offline."
                "vocab_empty" -> "Vocabulario Vacío"
                "vocab_empty_desc" -> "¡Al leer las historias, haz clic en las palabras naranjas para abrir la traducción y agregarlas aquí!"
                "meaning" -> "Significado"
                "example" -> "Ejemplo Práctico"
                "my_profile" -> "Mi Perfil"
                "student_of" -> "Estudiante de %s"
                "level" -> "Nivel"
                "native_in" -> "Nativo en %s"
                "daily_goal" -> "META DIARIA"
                "streak" -> "Racha"
                "days" -> "días"
                "publisher" -> "Publicador"
                "approved" -> "Aprobado"
                "pending" -> "Pendiente"
                "my_hobbies" -> "Mis Intereses y Hobbies"
                "reset_onboarding" -> "Reiniciar Configuración"
                "create_story" -> "Crear Nueva Historia"
                "publish_community" -> "Publica textos para la comunidad en %s"
                "orig_title" -> "Título Original (%s)"
                "trans_title" -> "Título Traducido (Español)"
                "story_text" -> "Texto de la Historia (%s)"
                "story_trans" -> "Traducción de la Historia (Español)"
                "diff_level" -> "Selecciona el Nivel de Dificuldade"
                "category" -> "Categoría"
                "cover_url" -> "URL de la Imagen de Portada (Opcional)"
                "tags" -> "Tags (separados por coma)"
                "publish_btn" -> "Publicar Historia"
                "fill_required" -> "¡Por favor, completa todos los campos obligatorios!"
                "publish_success" -> "¡Historia publicada con éxito!"
                "publish_locked" -> "Publicación Bloqueada"
                "publish_locked_desc" -> "Para publicar historias en %s, debes demostrar competencia y acertar el 100%% de nuestra prueba de 20 preguntas."
                "take_test" -> "Hacer Prueba de Competencia"
                "dict_tap" -> "Toca cualquier palabra resaltada para abrir el diccionario:"
                "prof_test" -> "Prueba de Competencia en %s"
                "test_desc" -> "¡Acierta el 100% (20/20) para desbloquear la publicación de historias!"
                "question" -> "Pregunta"
                "corrects" -> "Aciertos"
                "confirm" -> "Confirmar Respuesta"
                "test_finished" -> "¡Prueba Concluida!"
                "not_this_time" -> "¡No fue esta vez!"
                "got_correct" -> "Acertaste %d de %d preguntas (%d%%)"
                "pub_unlocked" -> "¡PUBLICACIÓN DESBLOQUEADA!"
                "congrats_desc" -> "¡Increíble! Acertaste todas las preguntas de competencia en %s. ¡Ahora estás autorizado a publicar nuevos textos!"
                "how_to_unlock" -> "¿Cómo desbloquear?"
                "unlock_desc" -> "Para mantener la calidad pedagógica, solo usuarios con 100% en la prueba pueden publicar historias. ¡Estudia más y vuelve a intentarlo!"
                "try_again" -> "Intentar de Nuevo"
                "original" -> "Original"
                "translation" -> "Traducción"
                "none" -> "Ninguno"
                else -> key
            }
            lang.contains("ingl") || lang.contains("english") -> when (key) {
                "step" -> "Step"
                "of" -> "of"
                "next" -> "Continue"
                "back" -> "Back"
                "finish" -> "Finish"
                "app_lang" -> "App Language"
                "native_lang" -> "Your Native Language"
                "secondary_lang" -> "Secondary Language (Optional)"
                "study_lang" -> "Language of Study"
                "lang_config" -> "Language Settings"
                "lang_subtitle" -> "Choose the languages you use and the one you want to study."
                "study_level" -> "Study Language Level"
                "level_desc" -> "Select your current level in %s. This helps adapt text difficulty."
                "choose_interests" -> "Choose Your Interests"
                "interests_desc" -> "We recommend texts based on selected subcategories."
                "reading" -> "Reading"
                "tests" -> "Tests"
                "vocabulary" -> "Vocabulary"
                "profile" -> "Profile"
                "publish" -> "Publish"
                "my_vocab" -> "My Vocabulary"
                "vocab_desc" -> "Words and phrases you saved during readings to study offline."
                "vocab_empty" -> "Empty Vocabulary"
                "vocab_empty_desc" -> "While reading stories, click on orange words to see translations and add them here!"
                "meaning" -> "Meaning"
                "example" -> "Practical Example"
                "my_profile" -> "My Profile"
                "student_of" -> "Student of %s"
                "level" -> "Level"
                "native_in" -> "Native in %s"
                "daily_goal" -> "DAILY GOAL"
                "streak" -> "Streak"
                "days" -> "days"
                "publisher" -> "Publisher"
                "approved" -> "Approved"
                "pending" -> "Pending"
                "my_hobbies" -> "My Interests & Hobbies"
                "reset_onboarding" -> "Reset Settings"
                "create_story" -> "Create New Story"
                "publish_community" -> "Publish texts for the community in %s"
                "orig_title" -> "Original Title (%s)"
                "trans_title" -> "Translated Title (English)"
                "story_text" -> "Story Text (%s)"
                "story_trans" -> "Story Translation (English)"
                "diff_level" -> "Select Difficulty Level"
                "category" -> "Category"
                "cover_url" -> "Cover Image URL (Optional)"
                "tags" -> "Tags (comma separated)"
                "publish_btn" -> "Publish Story"
                "fill_required" -> "Please fill in all required fields!"
                "publish_success" -> "Story published successfully!"
                "publish_locked" -> "Publishing Locked"
                "publish_locked_desc" -> "To publish stories in %s, you must prove proficiency by getting 100%% on our 20-question test."
                "take_test" -> "Take Proficiency Test"
                "dict_tap" -> "Tap any highlighted word to open the dictionary:"
                "prof_test" -> "Proficiency Test in %s"
                "test_desc" -> "Get 100% (20/20) to unlock story publishing!"
                "question" -> "Question"
                "corrects" -> "Correct"
                "confirm" -> "Confirm Answer"
                "test_finished" -> "Test Completed!"
                "not_this_time" -> "Not this time!"
                "got_correct" -> "You got %d out of %d questions correct (%d%%)"
                "pub_unlocked" -> "PUBLISHING UNLOCKED!"
                "congrats_desc" -> "Incredible! You got all questions correct. You are now authorized to publish new stories!"
                "how_to_unlock" -> "How to unlock?"
                "unlock_desc" -> "To ensure pedagogical quality, only users with 100% on the test can create stories. Study more and try again!"
                "try_again" -> "Try Again"
                "original" -> "Original"
                "translation" -> "Translation"
                "none" -> "None"
                else -> key
            }
            lang.contains("japo") || lang.contains("nihon") || lang.contains("日本語") -> when (key) {
                "step" -> "ステップ"
                "of" -> "/"
                "next" -> "次へ"
                "back" -> "戻る"
                "finish" -> "完了"
                "app_lang" -> "アプリ言語"
                "native_lang" -> "あなたの母国語"
                "secondary_lang" -> "第二言語（任意）"
                "study_lang" -> "学習言語"
                "lang_config" -> "言語設定"
                "lang_subtitle" -> "使用する言語と学習したい言語を選択してください。"
                "study_level" -> "学習言語のレベル"
                "level_desc" -> "%sの現在のレベルを選択してください。難易度調整に役立ちます。"
                "choose_interests" -> "興味のある分野"
                "interests_desc" -> "選択したサブカテゴリに基づいて記事を推薦します。"
                "reading" -> "読解"
                "tests" -> "テスト"
                "vocabulary" -> "単語帳"
                "profile" -> "プロフィール"
                "publish" -> "投稿"
                "my_vocab" -> "マイ語彙"
                "vocab_desc" -> "オフライン学習用に保存した単語やフレーズ。"
                "vocab_empty" -> "単語帳は空です"
                "vocab_empty_desc" -> "記事を読んでいるときに、オレンジ色の単語をタップして翻訳を表示し、ここに追加してください！"
                "meaning" -> "意味"
                "example" -> "実例"
                "my_profile" -> "マイプロフィール"
                "student_of" -> "%s 学習者"
                "level" -> "レベル"
                "native_in" -> "母国語: %s"
                "daily_goal" -> "今日の目標"
                "streak" -> "継続日数"
                "days" -> "日"
                "publisher" -> "投稿権限"
                "approved" -> "承認済み"
                "pending" -> "未承認"
                "my_hobbies" -> "趣味・関心"
                "reset_onboarding" -> "設定をリセット"
                "create_story" -> "新しいストーリーを作成"
                "publish_community" -> "%sでコミュニティ向けに記事を公開する"
                "orig_title" -> "原文タイトル (%s)"
                "trans_title" -> "翻訳タイトル (日本語)"
                "story_text" -> "ストーリー本文 (%s)"
                "story_trans" -> "ストーリー翻訳 (日本語)"
                "diff_level" -> "難易度を選択"
                "category" -> "カテゴリ"
                "cover_url" -> "カバー画像URL（任意）"
                "tags" -> "タグ（カンマ区切り）"
                "publish_btn" -> "ストーリーを公開"
                "fill_required" -> "必須フィールドをすべて入力してください！"
                "publish_success" -> "ストーリーを公開しました！"
                "publish_locked" -> "投稿がロックされています"
                "publish_locked_desc" -> "%sでストーリーを投稿するには、20問のテストで100%%の正解率を達成する必要があります。"
                "take_test" -> "実力テストを受ける"
                "dict_tap" -> "強調表示された単語をタップして辞書を開きます："
                "prof_test" -> "%sのレベルテスト"
                "test_desc" -> "ストーリー投稿をアンロックするには100%（20/20）正解してください！"
                "question" -> "質問"
                "corrects" -> "正解数"
                "confirm" -> "回答を確認"
                "test_finished" -> "テスト終了！"
                "not_this_time" -> "今回は残念でした！"
                "got_correct" -> "%d問中%d問正解（%d%%）"
                "pub_unlocked" -> "投稿機能アンロック！"
                "congrats_desc" -> "素晴らしい！全問正解しました。ストーリーの公開が承認されました！"
                "how_to_unlock" -> "アンロック方法"
                "unlock_desc" -> "教育的な品質を維持するため、全問正解者のみが投稿できます。もっと学習して再挑戦してください！"
                "try_again" -> "もう一度受ける"
                "original" -> "原文"
                "translation" -> "翻訳"
                "none" -> "なし"
                else -> key
            }
            lang.contains("grego") || lang.contains("greek") || lang.contains("el") -> when (key) {
                "step" -> "Βήμα"
                "of" -> "από"
                "next" -> "Συνέχεια"
                "back" -> "Πίσω"
                "finish" -> "Τέλος"
                "app_lang" -> "Γλώσσα Εφαρμογής"
                "native_lang" -> "Μητρική Γλώσσα"
                "secondary_lang" -> "Δεύτερη Γλώσσα (Προαιρετικά)"
                "study_lang" -> "Γλώσσα Εκμάθησης"
                "lang_config" -> "Ρυθμίσεις Γλωσσών"
                "lang_subtitle" -> "Επιλέξτε τις γλώσσες που χρησιμοποιείτε και αυτή που θέλετε να μάθετε."
                "study_level" -> "Επίπεδο Γλώσσας Εκμάθησης"
                "level_desc" -> "Επιλέξτε το τρέχον επίπεδό σας στα %s."
                "choose_interests" -> "Επιλέξτε Ενδιαφέροντα"
                "interests_desc" -> "Προτείνουμε κείμενα με βάση τις επιλογές σας."
                "reading" -> "Ανάγνωση"
                "tests" -> "Τεστ"
                "vocabulary" -> "Λεξιλόγιο"
                "profile" -> "Προφίλ"
                "publish" -> "Δημοσίευση"
                "my_vocab" -> "Το Λεξιλόγιό μου"
                "vocab_desc" -> "Λέξεις και εκφράσεις που αποθηκεύσατε για μελέτη εκτός σύνδεσης."
                "vocab_empty" -> "Κενό Λεξιλόγιο"
                "vocab_empty_desc" -> "Πατήστε τις πορτοκαλί λέξεις για να δείτε τη μετάφραση και να τις προσθέσετε εδώ!"
                "meaning" -> "Σημασία"
                "example" -> "Παράδειγμα"
                "my_profile" -> "Το Προφίλ μου"
                "student_of" -> "Μαθητής στα %s"
                "level" -> "Επίπεδο"
                "native_in" -> "Μητρική γλώσσα: %s"
                "daily_goal" -> "ΚΑΘΗΜΕΡΙΝΟΣ ΣΤΟΧΟΣ"
                "streak" -> "Σερί"
                "days" -> "ημέρες"
                "publisher" -> "Δημοσίευση"
                "approved" -> "Εγκεκριμένο"
                "pending" -> "Εκκρεμεί"
                "my_hobbies" -> "Ενδιαφέροντα & Χόμπι"
                "reset_onboarding" -> "Επαναφορά Ρυθμίσεων"
                "create_story" -> "Δημιουργία Ιστορίας"
                "publish_btn" -> "Δημοσίευση Ιστορίας"
                "fill_required" -> "Παρακαλώ συμπληρώστε όλα τα απαιτούμενα πεδία!"
                "publish_success" -> "Η ιστορία δημοσιεύτηκε με επιτυχία!"
                "publish_locked" -> "Κλειδωμένη Δημοσίευση"
                "try_again" -> "Δοκιμάστε Ξανά"
                "original" -> "Πρωτότυπο"
                "translation" -> "Μετάφραση"
                "none" -> "Κανένα"
                else -> key
            }
            lang.contains("russo") || lang.contains("russian") || lang.contains("ru") -> when (key) {
                "step" -> "Шаг"
                "of" -> "из"
                "next" -> "Продолжить"
                "back" -> "Назад"
                "finish" -> "Готово"
                "app_lang" -> "Язык приложения"
                "native_lang" -> "Родной язык"
                "secondary_lang" -> "Второй язык (Опционально)"
                "study_lang" -> "Изучаемый язык"
                "lang_config" -> "Языковые настройки"
                "lang_subtitle" -> "Выберите языки, которые вы используете и хотите изучать."
                "study_level" -> "Уровень изучаемого языка"
                "level_desc" -> "Выберите ваш текущий уровень в %s."
                "choose_interests" -> "Выберите интересы"
                "interests_desc" -> "Мы рекомендуем тексты на основе ваших предпочтений."
                "reading" -> "Чтение"
                "tests" -> "Тесты"
                "vocabulary" -> "Словарь"
                "profile" -> "Профиль"
                "publish" -> "Публикация"
                "my_vocab" -> "Мой словарь"
                "vocab_desc" -> "Слова и выражения, сохраненные вами для изучения офлайн."
                "vocab_empty" -> "Словарь пуст"
                "vocab_empty_desc" -> "Нажимайте на оранжевые слова при чтении, чтобы добавить их в словарь!"
                "meaning" -> "Значение"
                "example" -> "Пример"
                "my_profile" -> "Мой профиль"
                "student_of" -> "Изучает %s"
                "level" -> "Уровень"
                "native_in" -> "Родной язык: %s"
                "daily_goal" -> "ЕЖЕДНЕВНАЯ ЦЕЛЬ"
                "streak" -> "Серия"
                "days" -> "дней"
                "publisher" -> "Публикация"
                "approved" -> "Одобрено"
                "pending" -> "Ожидает"
                "my_hobbies" -> "Мои интересы и хобби"
                "reset_onboarding" -> "Сбросить настройки"
                "create_story" -> "Создать историю"
                "publish_btn" -> "Опубликовать"
                "fill_required" -> "Пожалуйста, заполните все обязательные поля!"
                "publish_success" -> "История успешно опубликована!"
                "publish_locked" -> "Публикация заблокирована"
                "try_again" -> "Попробовать снова"
                "original" -> "Оригинал"
                "translation" -> "Перевод"
                "none" -> "Нет"
                else -> key
            }
            // Default fallbacks for all other languages mapped to Portuguese
            else -> when (key) {
                "step" -> "Passo"
                "of" -> "de"
                "next" -> "Continuar"
                "back" -> "Voltar"
                "finish" -> "Finalizar"
                "app_lang" -> "Idioma do Aplicativo"
                "native_lang" -> "Seu Idioma Nativo"
                "secondary_lang" -> "Idioma Secundário (Opcional)"
                "study_lang" -> "Idioma em Estudo"
                "lang_config" -> "Configuração de Idiomas"
                "lang_subtitle" -> "Escolha os idiomas que você usa e o que deseja estudar."
                "study_level" -> "Nível do Idioma em Estudo"
                "level_desc" -> "Selecione o seu nível atual em %s. Isso ajudará a adaptar a dificuldade do vocabulário e dos textos."
                "choose_interests" -> "Escolha seus Interesses"
                "interests_desc" -> "Recomendamos textos com base nas subcategorias selecionadas."
                "reading" -> "Leitura"
                "tests" -> "Testes"
                "vocabulary" -> "Vocabulário"
                "profile" -> "Perfil"
                "publish" -> "Publicar"
                "my_vocab" -> "Meu Vocabulário"
                "vocab_desc" -> "Palavras e expressões que você salvou durante as leituras para estudar e revisar offline."
                "vocab_empty" -> "Vocabulário Vazio"
                "vocab_empty_desc" -> "Ao ler as histórias, clique nas palavras em laranja para abrir a tradução e adicioná-las aqui!"
                "meaning" -> "Significado"
                "example" -> "Exemplo Prático"
                "my_profile" -> "Meu Perfil"
                "student_of" -> "Estudante de %s"
                "level" -> "Nível"
                "native_in" -> "Nativo em %s"
                "daily_goal" -> "META DIÁRIA"
                "streak" -> "Ofensiva"
                "days" -> "dias"
                "publisher" -> "Publicador"
                "approved" -> "Aprovado"
                "pending" -> "Pendente"
                "my_hobbies" -> "Meus Interesses & Hobbies"
                "reset_onboarding" -> "Recomeçar Onboarding"
                "create_story" -> "Criar Nova História"
                "publish_community" -> "Publique textos para a comunidade em %s"
                "orig_title" -> "Título Original (%s)"
                "trans_title" -> "Título Traduzido (Português)"
                "story_text" -> "Texto da História (%s)"
                "story_trans" -> "Tradução do Texto (Português)"
                "diff_level" -> "Selecione o Nível de Dificuldade"
                "category" -> "Categoria"
                "cover_url" -> "URL da Imagem de Capa (Opcional)"
                "tags" -> "Tags (separadas por vírgula)"
                "publish_btn" -> "Publicar História"
                "fill_required" -> "Por favor, preencha todos os campos obrigatórios!"
                "publish_success" -> "História publicada com sucesso!"
                "publish_locked" -> "Publicação Bloqueada"
                "publish_locked_desc" -> "Para poder publicar novas histórias no idioma %s, você deve comprovar proficiência e gabaritar (100%% de acertos) o nosso teste de 20 questões de leitura."
                "take_test" -> "Fazer Teste de Proficiência"
                "dict_tap" -> "Toque em qualquer palavra em destaque para abrir o dicionário:"
                "prof_test" -> "Teste de Proficiência em %s"
                "test_desc" -> "Acerte 100% (20/20) para desbloquear a publicação de histórias!"
                "question" -> "Questão"
                "corrects" -> "Acertos"
                "confirm" -> "Confirmar Resposta"
                "test_finished" -> "Teste Concluído!"
                "not_this_time" -> "Não foi dessa vez!"
                "got_correct" -> "Você acertou %d de %d questões (%d%%)"
                "pub_unlocked" -> "PUBLICAÇÃO DESBLOQUEADA!"
                "congrats_desc" -> "Incrível! Você acertou todas as questões de proficiência de %s e provou ser fluente em sua leitura. Agora você está autorizado a publicar novos textos na plataforma e compartilhá-los com outros estudantes!"
                "how_to_unlock" -> "Como desbloquear?"
                "unlock_desc" -> "Para manter la qualidade pedagógica dos posts na plataforma, apenas usuários aprovados com 100% no teste de proficiência podem criar histórias. Estude mais os textos da WenLang e tente novamente!"
                "try_again" -> "Tentar Novamente"
                "original" -> "Original"
                "translation" -> "Tradução"
                "none" -> "Nenhum"
                else -> key
            }
        }
    }
}
